import type { Metadata } from 'next'
import Link from 'next/link'
import { LegalPage, LegalSection } from '@/components/legal/legal-page'
import { WebOnly } from '@/components/legal/web-only'
import { SUPPORT_PHONE, SUPPORT_PHONE_TEL } from '@/lib/legal/operator'
export const metadata: Metadata = { title: 'Privacy notice | Huddle', description: 'The data used by the current version of Huddle, its purposes, and available account and content controls.', alternates: { canonical: '/en/privacy', languages: { 'zh-TW': '/privacy', en: '/en/privacy' } } }
export default function PrivacyPage() {
  return <LegalPage page="privacy" locale="en" title="Privacy notice" intro="This notice describes the data used by the current version, what it is used for, and the controls available to you.">
    <LegalSection title="Your account and content"><p>Huddle is operated by an individual, who collects and processes the personal data described in this notice (contact details are in the operator section of our <Link href="/en/terms#operator">terms</Link>).</p><p>Huddle uses email addresses, account identifiers and authentication information to identify users. Your tasks, calendar entries, focus records, notes, whiteboards, uploaded images and preferences are used to provide your workspace, storage, syncing across devices and sharing features you enable.</p><p>You may browse the public website without creating an account. Without the information needed to sign in, you cannot use the cloud workspace features that require an account. You decide what work content to enter.</p></LegalSection>
    <LegalSection title="Service providers and device storage"><p>Huddle uses Supabase for authentication, application data and uploaded files, Zeabur to host the website, and Sentry for error reports. Google or Apple participates in authentication when you choose its sign-in option. Your browser and desktop app store sign-in state, some settings and necessary cached data. The desktop app connects to the same online service.</p><WebOnly><p>Once website purchases open, card payments for Huddle Pro bought on the website will be processed by SHOPLINE Payments; see “Subscriptions and payment data” below.</p></WebOnly><p>Network connections and system operation also involve technical information about networks and devices. Cloud providers may process data across regions. This notice does not claim that data is stored only in Taiwan or that every record is immediately erased when an account is deleted.</p></LegalSection>
    <LegalSection title="Error reporting (Sentry)"><p>When Huddle hits a software error on your device, it automatically sends an error report to the error-monitoring service Sentry (Functional Software, Inc.) so we can find and fix the problem. Data is sent only at the moment an error happens; nothing is sent when there is no error. This applies to the website, the iPhone app and the desktop app.</p><p>What we collect: the type of error and a short description (truncated, with personal information masked on a best-effort basis), the page path where it happened (without anything after the “?” in the address, and with identifiers in the path masked), device and browser or operating-system version, the Huddle app version, your account number (a random system-generated string, not your email or name, used to tell how many people an error affects and to find related reports when you contact us), and a short trail of what happened just before the error (for example which page you moved to and which backend address path was called). What we do not collect: your tasks, calendar entries, notes, whiteboards or uploaded files; your email or name; sign-in credentials or cookies. We do not record your screen or your activity. Only we can link the account number in an error report to your account; Sentry and others cannot tell who you are from it. The error description is automatically generated text; we mask personal content that may appear in it (such as emails, quoted text and non-English text) automatically and on a best-effort basis, but we cannot guarantee that every piece is caught.</p><p>Where it is stored: the United States. Sentry may process this data outside your region. On Sentry’s free plan, error data is kept for 30 days by default and then deleted automatically; if we move to a paid plan the period may differ and this page will be updated. This data is used only to diagnose and fix errors. It is not used for advertising and is not sold.</p></LegalSection>
    <LegalSection title="AI meeting summaries"><p>When you paste a meeting transcript or notes, that text is sent to OpenAI (model gpt-4.1-mini) to generate a summary and suggested tasks. Under <a href="https://developers.openai.com/api/docs/guides/your-data" target="_blank" rel="noopener noreferrer">OpenAI’s API data policy</a>, content sent through the API is not used to train its models by default, and we have turned off storing these requests in our OpenAI account. OpenAI may still retain the content for up to 30 days for abuse monitoring (longer only where required by law or reasonably necessary to prevent harm). This feature has a monthly per-person limit, and nothing is sent unless you actively use it. Avoid pasting confidential or sensitive content that others have not agreed to share.</p></LegalSection>
    <LegalSection title="Google Calendar (optional)"><p>If you choose to connect Google Calendar, Huddle reads your primary calendar with read-only access to show your meetings on your calendar; event content is not stored on our servers. When a share partner looks for a meeting time with you, your Google meeting times are treated as busy — only start and end times are used, never titles, locations or other details. You can turn this off in settings or disconnect at any time. Huddle’s use and transfer of information received from Google APIs will adhere to the <a href="https://developers.google.com/terms/api-services-user-data-policy" target="_blank" rel="noopener noreferrer">Google API Services User Data Policy</a>, including the Limited Use requirements.</p></LegalSection>
    <LegalSection title="Sharing"><p>Check the recipients and scope before enabling sharing. Downloading the desktop app does not automatically publish your personal workspace content on the website; the website uses illustrative content. Recipients may keep separate copies of information you choose to share with them.</p></LegalSection>
    <LegalSection title="Managing, retaining and deleting data"><p>You can view, edit and delete content in the product, and select “Delete account” in settings. Deletion is irreversible, so preserve anything you need first. If the operation fails, do not treat the error message as confirmation that deletion has succeeded.</p><p>Data needed to provide the features is retained while you use the service. The scope and timing of removal may differ for accounts, uploaded files, backups and system logs. This notice does not promise that all copies are immediately erased. Deleting your account does not cancel a subscription bought through the App Store, so cancel it in your Apple Account first. <WebOnly>Once website purchases open, deleting your account will also stop renewal of a subscription bought on the website. </WebOnly>Transaction and billing records that the law requires us to keep are not covered by immediate deletion (see “Subscriptions and payment data”).</p></LegalSection>
    <LegalSection title="Your personal data rights"><p>Under applicable law, you may request access to or copies of your personal data, supplementation or correction, cessation of collection, processing or use, and deletion. The product provides content editing and account deletion controls. For other requests, call <a href={SUPPORT_PHONE_TEL}>{SUPPORT_PHONE}</a>. We will confirm that you own the account and reply as soon as we can. Do not submit identification documents or private content to the public GitHub discussion area.</p><p>For these rights, see <a href="https://law.moj.gov.tw/LawClass/LawAll.aspx?pcode=I0050021" target="_blank" rel="noreferrer">Article 3 of Taiwan’s Personal Data Protection Act (Chinese)</a>. For general usage guidance, visit our <Link href="/en/support">help page</Link>.</p></LegalSection>
    <LegalSection title="Subscriptions and payment data"><p>Pro payment flows are not currently enabled. Before introducing Apple, Google Play or subscription management services, this notice will be updated to describe transaction data, subscription identifiers and the relevant providers’ processing. Creating an account does not create a subscription.</p><p><strong>iPhone app purchases (App Store) — applies once purchases open</strong></p><p>When you buy Huddle Pro in the iPhone app, Apple processes the payment; we never receive your card or Apple Account payment details. To confirm and manage your subscription status we use RevenueCat, Inc. (United States) as our subscription management provider: we give it your Huddle account identifier, and it obtains your purchase records from Apple (plan, purchase and expiry times, transaction identifiers, refunds). This data is stored in the United States and used only to activate, renew and restore your subscription, for support and for reconciliation — never for advertising, and it is never sold.</p><p>When you delete your Huddle account, we also ask RevenueCat to delete your subscription records; if its systems are temporarily unavailable we retry automatically and complete this within 7 days at the latest. Transaction records Apple keeps under its own policies are handled by Apple.</p>
      <WebOnly>
        <p><strong>Website purchases (credit card) — applies once website purchases open</strong></p>
        <p>To take payment, activate and renew Huddle Pro, handle the free trial, send receipts, handle cancellations and refunds, provide support and reconciliation, and keep billing records as required by law, once website purchases open we will process: your account email and account ID; the plan you chose and your trial status; the amount, currency, and payment and renewal dates; order and transaction IDs; the result of each charge; refund records; and card information returned by SHOPLINE Payments (card brand, issuing country and the last four digits of the card number).</p>
        <p>Card payments are processed by SHOPLINE Payments (S Technology Co., Ltd.). The card number, expiry date, cardholder name and other details you enter on the payment screen go directly to SHOPLINE Payments, which collects, processes and stores them under its own privacy policy (which states that data is stored in Singapore and the United States). Huddle never receives or stores your full card number. With your authorization, SHOPLINE Payments keeps your payment details for the automatic charge when a trial ends and for renewals, and Huddle keeps only the token it provides so we can charge on the charge date.</p>
        <p><strong>Who processes it, where, and for how long</strong></p>
        <p>This data is used only to provide and manage your subscription, provide support, reconcile payments, prevent fraud and chargebacks, and meet legal obligations. It is not used for advertising and is not sold. It is shared only with: the operator of Huddle; SHOPLINE Payments (card payments); our cloud providers (Supabase and Zeabur); and authorities entitled to it by law, such as tax authorities. It may be processed outside Taiwan, including in Singapore and the United States.</p>
        <p>Entitlement records are kept while your account exists. Transaction, receipt and refund records are accounting records, so they are kept for as long as tax and accounting laws require even if you delete your account, and then deleted.</p>
        <p><strong>If you choose not to provide it</strong></p>
        <p>You can keep using the free plan without buying Pro. To start a Pro trial or buy Pro, you need to provide payment details; without them, we cannot activate Pro or take payment.</p>
      </WebOnly>
      <p>If our data practices change, the content and date of this notice will be updated. Where separate consent is required, it will be addressed in the relevant interaction.</p></LegalSection>
  </LegalPage>
}
