import type { Metadata } from 'next'
import Link from 'next/link'
import { LegalPage, LegalSection } from '@/components/legal/legal-page'
export const metadata: Metadata = { title: 'Privacy notice | Huddle', description: 'The data used by the current version of Huddle, its purposes, and available account and content controls.', alternates: { canonical: '/en/privacy', languages: { 'zh-TW': '/privacy', en: '/en/privacy' } } }
export default function PrivacyPage() {
  return <LegalPage page="privacy" locale="en" title="Privacy notice" intro="This notice describes the data used by the current version, what it is used for, and the controls available to you.">
    <LegalSection title="Your account and content"><p>Huddle uses email addresses, account identifiers and authentication information to identify users. Your tasks, calendar entries, focus records, notes, whiteboards, uploaded images and preferences are used to provide your workspace, storage, syncing across devices and sharing features you enable.</p><p>You may browse the public website without creating an account. Without the information needed to sign in, you cannot use the cloud workspace features that require an account. You decide what work content to enter.</p></LegalSection>
    <LegalSection title="Service providers and device storage"><p>Huddle uses Supabase for authentication, application data and uploaded files, and Zeabur to host the website. Google or Apple participates in authentication when you choose its sign-in option. Your browser and desktop app store sign-in state, some settings and necessary cached data. The desktop app connects to the same online service.</p><p>Network connections and system operation also involve technical information about networks and devices. Cloud providers may process data across regions. This notice does not claim that data is stored only in Taiwan or that every record is immediately erased when an account is deleted.</p></LegalSection>
    <LegalSection title="Sharing"><p>Check the recipients and scope before enabling sharing. Downloading the desktop app does not automatically publish your personal workspace content on the website; the website uses illustrative content. Recipients may keep separate copies of information you choose to share with them.</p></LegalSection>
    <LegalSection title="Managing, retaining and deleting data"><p>You can view, edit and delete content in the product, and select “Delete account” in settings. Deletion is irreversible, so preserve anything you need first. If the operation fails, do not treat the error message as confirmation that deletion has succeeded.</p><p>Data needed to provide the features is retained while you use the service. The scope and timing of removal may differ for accounts, uploaded files, backups and system logs. This notice does not promise that all copies are immediately erased. Account deletion is also separate from cancelling any subscription you may purchase through an app store in the future.</p></LegalSection>
    <LegalSection title="Your personal data rights"><p>Under applicable law, you may request access to or copies of your personal data, supplementation or correction, cessation of collection, processing or use, and deletion. The product provides content editing and account deletion controls. A dedicated private channel for other requests is not currently available through this page. Do not submit identification documents or private content to the public GitHub discussion area.</p><p>For these rights, see <a href="https://law.moj.gov.tw/LawClass/LawAll.aspx?pcode=I0050021" target="_blank" rel="noreferrer">Article 3 of Taiwan’s Personal Data Protection Act (Chinese)</a>. For general usage guidance, visit our <Link href="/en/support">help page</Link>.</p></LegalSection>
    <LegalSection title="Subscriptions and notice updates"><p>Pro payment flows are not currently enabled. Before introducing Apple, Google Play or subscription management services, this notice will be updated to describe transaction data, subscription identifiers and the relevant providers’ processing. Creating an account does not create a subscription.</p><p>If data processing practices change, the content and date of this notice will be updated. Where separate consent is required, it will be addressed in the relevant interaction.</p></LegalSection>
  </LegalPage>
}
