import type { Metadata } from 'next'
import Link from 'next/link'
import { LegalPage, LegalSection } from '@/components/legal/legal-page'
import { WebOnly } from '@/components/legal/web-only'
import { SUPPORT_EMAIL, SUPPORT_PHONE, SUPPORT_PHONE_TEL } from '@/lib/legal/operator'
import { IN_APP_PURCHASE_LIVE } from '@/lib/legal/in-app-purchase'

export const metadata: Metadata = { title: 'Cancellation and refunds | Huddle', description: IN_APP_PURCHASE_LIVE ? 'How Huddle Pro is billed through Apple, how to cancel renewal and request a refund, and your withdrawal rights.' : 'Current billing status, how cancellation, the free trial and refunds will work once website purchases open, and official app store refund resources.', alternates: { canonical: '/en/refunds', languages: { 'zh-TW': '/refunds', en: '/en/refunds' } } }
export default function RefundsPage() {
  return <LegalPage page="refunds" locale="en" title="Cancellation and refunds" intro="Stopping renewal, requesting a refund and deleting an account are separate actions, and how you do each depends on where you bought. Here is how they differ, with links to official guidance.">
    <LegalSection title={IN_APP_PURCHASE_LIVE ? 'How Huddle Pro is billed' : 'No Huddle subscription charges are currently active'}>{IN_APP_PURCHASE_LIVE ? <><p>Huddle Pro is an auto-renewing subscription that you can buy in the iPhone app through the App Store. Apple charges the payment method on your Apple Account and sends the receipt. The monthly plan is charged once a month and the annual plan once a year; the price and free-trial eligibility are those shown on the App Store purchase screen. You do not need to provide any payment details to create a Huddle account or sign in.</p><p>If you see a Huddle charge you do not recognize, first check the item and purchasing account on your Apple receipt, then call <a href={SUPPORT_PHONE_TEL}>{SUPPORT_PHONE}</a>. Do not post receipts, card numbers or personal information on a public issue page.</p></> : <><p>Pro is not available for purchase, so there are currently no Huddle subscriptions and no automatic charges when a trial ends. If you see a charge that appears to be from Huddle, first check the merchant, item and purchasing account on your bank or store receipt, and call <a href={SUPPORT_PHONE_TEL}>{SUPPORT_PHONE}</a>. Do not post receipts, card numbers or personal information on a public issue page.</p></>}</LegalSection>
    <WebOnly>
      <LegalSection id="web-trial" title="Website purchases: free trial and cancelling (applies once website purchases open)">
        <p><strong>Website purchases are not available yet.</strong> The “Website purchases” sections on this page apply only after Huddle opens purchasing on the website.</p>
        <p><strong>2-week free trial.</strong> When you start Pro on the website for the first time, you can get a 2-week free trial; a credit card is required. You are not charged during the trial, and the first period is charged automatically when it ends. <strong>If you cancel during the trial, you will not be charged.</strong> Each person gets one trial, whether you used it earlier in the iOS app or on the website.</p>
        <p><strong>Cancelling renewal (including cancelling a trial).</strong> Sign in to Huddle, go to Settings → Subscription and select Cancel renewal. You can cancel online at any time, without giving a reason. You can also call <a href={SUPPORT_PHONE_TEL}>{SUPPORT_PHONE}</a> and we will cancel for you. After you cancel, you will not be charged again. Pro stays available until the end of the period you have paid for (or the trial), and your account then returns to the free plan. To avoid the next charge, cancel before the end of the day before your renewal date. Cancelling renewal is not the same as requesting a refund — see the next section.</p>
      </LegalSection>
      <LegalSection id="web-refund" title="Website purchases: full refund within 7 days (applies once website purchases open)">
        <p>Within 7 days after the <strong>first charge following your trial</strong> (monthly or annual), you can withdraw from the subscription without giving a reason, and we will give you a <strong>full refund</strong> with no fees. The same full refund applies within 7 days after an <strong>annual plan renewal</strong> charge.</p>
        <p>To request it, select Request a refund under Settings → Subscription after signing in, or call <a href={SUPPORT_PHONE_TEL}>{SUPPORT_PHONE}</a> and give the email address of your Huddle account. The 7 days start the day after the payment, and your request only needs to be made before the end of the 7th day.</p>
        <p>Refunds go back to the original card. We will process the refund within 15 days starting the day after we receive your request; when it appears on your statement depends on your card issuer. Once refunded, Pro for that period stops and your account returns to the free plan. Your data is not deleted.</p>
        <p><strong>After 7 days</strong>, we do not give pro-rata refunds for monthly or annual periods already paid for, but you can cancel renewal at any time and keep Pro until the end of the period.</p>
        <p><strong>We always refund, regardless of the 7-day window</strong>, if you were charged twice, charged the wrong amount, charged after cancelling, or charged because someone else used your account without permission — and if we discontinue Huddle Pro or the service (pro-rata for unused days).</p>
      </LegalSection>
      <LegalSection id="web-failed" title="Website purchases: failed renewal payments (applies once website purchases open)">
        <p>If a renewal charge fails (for example, because the card has expired or reached its limit), we will email you and retry up to 3 times over the next 7 days, during which Pro stays available. You can update your card under Settings → Subscription. If payment still fails after 7 days, the subscription ends and your account returns to the free plan. We will not pursue payment for that period, and your data is not deleted. You can buy Pro again at any time.</p>
      </LegalSection>
    </WebOnly>
    <LegalSection title={IN_APP_PURCHASE_LIVE ? 'Cancelling renewal and requesting a refund (Apple)' : 'If you purchase through Apple in the future'}>{IN_APP_PURCHASE_LIVE ? <><p>For a subscription bought through the App Store, manage renewal in your Apple Account (on your iPhone or iPad, go to Settings → your name → Subscriptions), or follow <a href="https://support.apple.com/118428" target="_blank" rel="noreferrer">Apple’s cancellation instructions</a>. After you cancel, you will not be charged again and Pro stays available until the end of the period you have paid for. To request a refund, use <a href="https://support.apple.com/118223" target="_blank" rel="noreferrer">Apple’s official refund process</a>; Apple reviews refund requests. Cancelling renewal does not itself submit a refund request.</p></> : <><p>If App Store subscriptions become available, you can manage renewal in your Apple Account by following <a href="https://support.apple.com/118428" target="_blank" rel="noreferrer">Apple’s cancellation instructions</a>. To request a refund, use <a href="https://support.apple.com/118223" target="_blank" rel="noreferrer">Apple’s official refund process</a>. Cancelling renewal does not itself submit a refund request. Apple subscriptions cannot be cancelled or refunded on the Huddle website.</p></>}</LegalSection>
    <LegalSection title="If you purchase through Google Play in the future"><p>If Google Play subscriptions become available, you can manage and cancel them in the <a href="https://play.google.com/store/account/subscriptions" target="_blank" rel="noreferrer">Google Play subscription center</a>. For refunds, consult <a href="https://support.google.com/googleplay/answer/2479637?hl=en" target="_blank" rel="noreferrer">Google Play’s official refund guidance</a>. Make sure you are signed into the account used for the purchase. The remaining access period and refund outcome will be handled under applicable law and the original purchasing platform’s process.</p></LegalSection>
    <LegalSection title="Withdrawal and your rights"><p>Under Taiwan’s Consumer Protection Act, consumers who buy a service online can generally withdraw from the contract within seven days after receiving the service, without giving a reason and at no cost. An ongoing subscription service cannot declare all payments non-refundable solely because it is digital. Huddle does not impose a blanket waiver of withdrawal rights or an “all payments are non-refundable” term, and nothing on this page limits rights protected by law.</p><ul><WebOnly><li><strong>Website purchases</strong> (once open): see “Website purchases: full refund within 7 days” above.</li></WebOnly>{IN_APP_PURCHASE_LIVE ? <li><strong>Purchases through Apple</strong>: Apple collects the payment, so first request a refund from Apple as described above. If you are a consumer in Taiwan and want to withdraw within 7 days after the first charge following your trial (or within 7 days after an annual plan renewal charge), also call <a href={SUPPORT_PHONE_TEL}>{SUPPORT_PHONE}</a> or email <a href={`mailto:${SUPPORT_EMAIL}`}>{SUPPORT_EMAIL}</a> and have your Huddle account email and the order ID on your Apple receipt ready. We will complete the refund within 15 days starting the day after we receive your notice: if Apple approves it, Apple’s refund applies; if Apple has not approved it within that time, we will refund that period’s payment by bank transfer (you will need to give us account details), and we will not rely on Apple’s decision as a reason to refuse.</li> : <li><strong>Purchases through Apple</strong> (once open): Apple collects the payment, so request a refund from Apple as described above; call <a href={SUPPORT_PHONE_TEL}>{SUPPORT_PHONE}</a> if you need help.</li>}</ul>{IN_APP_PURCHASE_LIVE && <p>For purchases outside Taiwan, refund eligibility depends on local law and Apple’s terms for your region. Nothing on this page limits consumer rights that you have under the law of your place of residence and that cannot be excluded by agreement.</p>}<p>See <a href="https://law.moj.gov.tw/LawClass/LawAll.aspx?pcode=J0170001" target="_blank" rel="noreferrer">Articles 18, 19 and 19-2 of Taiwan’s Consumer Protection Act (Chinese)</a>.</p></LegalSection>
    <LegalSection title="Deleting your account and subscriptions"><p>Uninstalling the app or deleting your Huddle account does not replace the Apple or Google Play cancellation process. For a subscription bought through Apple, cancel renewal in your Apple Account first, then delete your Huddle account.</p><WebOnly><p>Once website purchases open, deleting your account will also stop renewal of a subscription bought on the website, so you will not be charged again. It does not by itself refund a paid period; if you are still within the 7-day full-refund window, <strong>request the refund before deleting your account</strong>, as we cannot verify your identity afterwards.</p></WebOnly><p>For product questions, see our <Link href="/en/support">help page</Link>.</p></LegalSection>
  </LegalPage>
}
