import type { Metadata } from 'next'
import Link from 'next/link'
import { LegalPage, LegalSection } from '@/components/legal/legal-page'
export const metadata: Metadata = { title: 'Cancellation and refunds | Huddle', description: 'Current billing status, future subscription cancellation guidance and official app store refund resources.', alternates: { canonical: '/en/refunds', languages: { 'zh-TW': '/refunds', en: '/en/refunds' } } }
export default function RefundsPage() {
  return <LegalPage page="refunds" locale="en" title="Cancellation and refunds" intro="Stopping renewal, requesting a refund and deleting an account are separate actions. Here is how they differ, with links to official store guidance.">
    <LegalSection title="No Huddle subscription charges are currently active"><p>Pro is not available for purchase, and there is no arrangement that automatically charges you when a trial ends. If you see a charge that appears to be from Huddle, first check the merchant, item and purchasing account on your bank or store receipt. Do not post receipts, card numbers or personal information on a public issue page.</p></LegalSection>
    <LegalSection title="If you purchase through Apple in the future"><p>If App Store subscriptions become available, you can manage renewal in your Apple Account by following <a href="https://support.apple.com/118428" target="_blank" rel="noreferrer">Apple’s cancellation instructions</a>. To request a refund, use <a href="https://support.apple.com/118223" target="_blank" rel="noreferrer">Apple’s official refund process</a>. Cancelling renewal does not itself submit a refund request.</p></LegalSection>
    <LegalSection title="If you purchase through Google Play in the future"><p>If Google Play subscriptions become available, you can manage and cancel them in the <a href="https://play.google.com/store/account/subscriptions" target="_blank" rel="noreferrer">Google Play subscription center</a>. For refunds, consult <a href="https://support.google.com/googleplay/answer/2479637?hl=en" target="_blank" rel="noreferrer">Google Play’s official refund guidance</a>. Make sure you are signed into the account used for the purchase. The remaining access period and refund outcome will be handled under applicable law and the original purchasing platform’s process.</p></LegalSection>
    <LegalSection title="Withdrawal and your rights"><p>Taiwan’s distance-selling rules generally provide a statutory seven-day right to withdraw, subject to statutory exceptions. An ongoing subscription service cannot declare all payments non-refundable solely because it is digital. Huddle does not currently impose a blanket waiver of withdrawal rights or an “all payments are non-refundable” term. Before paid services become available, the applicable terms will be explained for the actual transaction without affecting rights protected by law.</p><p>See <a href="https://law.moj.gov.tw/LawClass/LawAll.aspx?pcode=J0170001" target="_blank" rel="noreferrer">Articles 18, 19 and 19-2 of Taiwan’s Consumer Protection Act (Chinese)</a>.</p></LegalSection>
    <LegalSection title="Deleting an account does not cancel renewal"><p>Uninstalling the app or deleting your Huddle account does not replace the original purchasing platform’s cancellation process. If you have a subscription in the future, check its renewal status before deleting your account. For current product questions, see our <Link href="/en/support">help page</Link>.</p></LegalSection>
  </LegalPage>
}
