import type { Metadata } from 'next'
import Link from 'next/link'
import { LegalPage, LegalSection, OperatorBlock } from '@/components/legal/legal-page'
import { WebOnly } from '@/components/legal/web-only'
import { COURT, SUPPORT_PHONE, SUPPORT_PHONE_TEL } from '@/lib/legal/operator'
import { IN_APP_PURCHASE_LIVE } from '@/lib/legal/in-app-purchase'

export const metadata: Metadata = { title: 'Terms of use | Huddle', description: IN_APP_PURCHASE_LIVE ? 'How Huddle works, how to manage your account and content, and how Huddle Pro subscriptions are billed, renewed, cancelled and refunded.' : 'How Huddle works, how to manage your account and content, and how Huddle Pro subscriptions will be billed, renewed, cancelled and refunded once website purchases open.', alternates: { canonical: '/en/terms', languages: { 'zh-TW': '/terms', en: '/en/terms' } } }
export default function TermsPage() {
  return <LegalPage page="terms" locale="en" title="Terms of use" intro="Learn what Huddle provides, how to use it, and how to manage your content and account.">
    <LegalSection title="What Huddle provides"><p>Huddle is a personal workspace for tasks, calendars, focus sessions, notes and whiteboards. The web and desktop apps sync through the same account. Signing in, accessing cloud content and syncing require an internet connection. Refer to the website’s download section for desktop beta installation instructions and supported platforms.</p></LegalSection>
    <LegalSection title="Your account and safe use"><p>Use only sign-in credentials you are authorized to use, and keep passwords and verification links secure. Do not use someone else’s account, access content without permission, distribute malicious software or interfere with the service.</p><p>You must be legally able to enter into a contract to purchase Huddle Pro. If you are a minor, get permission from your parent or legal guardian before purchasing. If you believe someone else is using your account, call <a href={SUPPORT_PHONE_TEL}>{SUPPORT_PHONE}</a> right away. We will suspend further charges and renewals on that account and help you resolve the issue.</p></LegalSection>
    <LegalSection title="Your content and sharing"><p>Using Huddle does not transfer ownership of the tasks, notes or images you create or upload. The service needs to process that content to display, store and sync it, and to carry out sharing you choose to enable. Only upload material you have the right to use. Check the recipients and scope before sharing, and do not share others’ confidential information or content that infringes their rights.</p></LegalSection>
    <LegalSection title={IN_APP_PURCHASE_LIVE ? 'Free features and Huddle Pro subscriptions' : 'Free access and planned subscriptions'}>{IN_APP_PURCHASE_LIVE ? <><p>Core features for tasks, calendars, focus sessions, notes and whiteboards are currently free to use and do not require a subscription. An existing free account will not automatically become a paid subscription; a subscription starts only after you actively confirm it on the purchase screen.</p><p>Huddle Pro is an optional paid plan that you can subscribe to in the iPhone app through the App Store, billed monthly or annually. It renews automatically until you cancel. The features included, price, billing period and free-trial eligibility are those shown on the App Store purchase screen before you confirm. Apple charges the payment method on your Apple Account; Huddle never receives your card number.</p><p>Huddle Pro bought through the App Store is linked to the Huddle account you are signed in to when you buy or tap “Restore purchases”. If you tap “Restore purchases” in a different Huddle account with the same Apple Account, the subscription moves to that account and the previous account loses Pro; only one account has it at a time. Apple handles billing, renewal, cancellation and refunds for App Store subscriptions under its own terms. To stop renewal, cancel in the subscription settings of your Apple Account; Pro stays available until the end of the period you have paid for. Deleting your Huddle account does not cancel the subscription or stop the charges. See <Link href="/en/refunds">Cancellation and refunds</Link> for refunds.</p></> : <><p>Pro subscriptions are not currently available for purchase. The website’s planned Taiwan prices of TWD 150 per month and TWD 990 per year are proposals, not active offers for purchase. If subscriptions become available, the actual features, billing period, price, automatic renewal terms and cancellation process will be shown before you confirm payment. An existing free account will not automatically become a paid subscription.</p><p>The planned prices are in New Taiwan dollars and include any applicable tax, with no additional fees.</p><p>Once iPhone purchases open, Huddle Pro bought through the App Store is linked to the Huddle account you are signed in to when you buy or tap “Restore purchases”. If you tap “Restore purchases” in a different Huddle account with the same Apple Account, the subscription moves to that account and the previous account loses Pro; only one account has it at a time. Apple handles billing, renewal, cancellation and refunds for App Store subscriptions under its own terms; deleting your Huddle account does not cancel the subscription or stop the charges.</p></>}<WebOnly><p>Once website purchases open, Pro is planned to include a 2-week free trial; see “Website purchases” below.</p></WebOnly></LegalSection>
    <WebOnly>
      <LegalSection id="web-billing" title="Website purchases: free trial, payment and auto-renewal (applies once website purchases open)">
        <p><strong>Website purchases are not available yet.</strong> The terms below apply only after Huddle opens purchasing on the website. Until then there are no subscriptions, trials or charges.</p>
        <p><strong>2-week free trial.</strong> When you start Pro on the website for the first time, you can get a 2-week free trial. Starting the trial requires a credit card; you are not charged during the trial, and when it ends the first period is charged automatically to that card. If you cancel during the trial, you will not be charged. Each person gets one free trial, whether you used it earlier in the iOS app or on the website. An account that has already used a trial does not get another one and is charged when it confirms the purchase.</p>
        <p><strong>Payment and activation.</strong> The website is planned to accept credit cards only and does not offer instalment plans. Card payments are processed by SHOPLINE Payments (S Technology Co., Ltd.); Huddle never receives or stores your full card number. With your authorization, SHOPLINE Payments keeps the card’s payment details so the subscription can renew. Pro is an online service that is available as soon as it is activated; nothing is shipped.</p>
        <p><strong>Auto-renewal.</strong> Your subscription renews automatically until you cancel. The monthly plan is charged once a month and the annual plan once a year, on the same day of the month (or year) as your first charge. If that day does not exist in a given month (for example, the 31st), you are charged on the last day of that month. After each successful charge, we email a receipt to your account address. For annual plans, we email you a reminder with the renewal date and amount at least 7 days before renewal.</p>
        <p><strong>Cancelling renewal.</strong> You can cancel at any time online: sign in to Huddle, go to Settings → Subscription and select Cancel renewal. No phone call is needed, though you can also call <a href={SUPPORT_PHONE_TEL}>{SUPPORT_PHONE}</a> and we will cancel for you. After you cancel, you will not be charged again and Pro stays available until the end of the period you have paid for (or the trial); your account then returns to the free plan. See <Link href="/en/refunds">Cancellation and refunds</Link> for refund rules.</p>
        <p><strong>Failed payments.</strong> If a renewal charge fails, we will email you and retry up to 3 times over the next 7 days, during which Pro stays available. You can update your card under Settings → Subscription. If payment still fails after 7 days, the subscription ends and your account returns to the free plan. We will not pursue payment for that period, and your data is not deleted because of it.</p>
        <p><strong>Price changes.</strong> If the subscription price changes, we will email you at least 30 days before the new price takes effect. The new price applies only from the first billing period after that notice; we never charge extra for a period you have already paid for. If you do not accept the new price, you can cancel renewal before it takes effect.</p>
        <p><strong>If you also subscribe through Apple.</strong> An Apple subscription and a website subscription are separate and do not cancel each other. If you already subscribe to Pro through Apple, please do not buy again on the website. If you are charged twice by mistake, call us and we will refund the website charge.</p>
      </LegalSection>
    </WebOnly>
    <LegalSection title="Updates and keeping your content"><p>Huddle continues to receive improvements and fixes. Maintenance or network outages may temporarily affect access. Keep your own copies of important content. If syncing fails, preserve any unsynced work before following the guidance on our <Link href="/en/support">help page</Link>.</p><p>If we change paid terms or anything that affects your existing rights, we will notify you at least 30 days in advance. If we decide to discontinue Huddle Pro or the service as a whole, we will give at least 30 days’ notice and refund, on a pro-rata basis, any days you have paid for but not used. We will not terminate your subscription arbitrarily. We may do so only if you seriously breach these terms (for example, by attacking our systems or distributing malware), and even then we will refund unused days on a pro-rata basis unless the law provides otherwise. These terms do not exclude your statutory rights or any liability that cannot lawfully be excluded.</p></LegalSection>
    <LegalSection title="Account deletion and reporting issues"><p>You can choose “Delete account” in Huddle’s settings and confirm the operation. Save any content you need first. Read our <Link href="/en/privacy">privacy notice</Link> for information about deletion and data processing. Deleting your account or uninstalling the app does <strong>not</strong> cancel a subscription bought through the App Store; cancel it first in the subscription settings of your Apple Account.</p><WebOnly><p>Once website purchases open, deleting your account will also stop renewal of a subscription bought on the website, so you will not be charged again.</p></WebOnly><p>Ways to report technical issues, and how to contact us about billing, refunds, complaints and personal data requests, are listed on our <Link href="/en/support">help page</Link>. If a dispute arises, please call us first; we will reply as soon as we can and work with you to resolve it. If it cannot be resolved, consumers in Taiwan may also file a complaint with a consumer service center or consumer protection officer of their city or county government under the Consumer Protection Act.</p>{IN_APP_PURCHASE_LIVE ? null : <p>This page does not mean that Huddle has enabled billing, received app store approval or passed a payment provider’s review.</p>}</LegalSection>
    <OperatorBlock english />
    <LegalSection id="law" title="Governing law and jurisdiction"><p>These terms are governed by the laws of the Republic of China (Taiwan). If a dispute about these terms or the Huddle service needs to go to court, {COURT.en} will be the court of first instance. This does not affect your right under Article 47 of the Consumer Protection Act to sue in the court of the place where the consumer relationship arose, or the jurisdiction rules for small-claims proceedings under the Code of Civil Procedure. Any ambiguity in these terms will be interpreted in favor of the consumer. Nothing in these terms limits rights that you have under law and that cannot be excluded by agreement.</p></LegalSection>
  </LegalPage>
}
