import type { Metadata } from 'next'
import Link from 'next/link'
import { LegalPage, LegalSection } from '@/components/legal/legal-page'

export const metadata: Metadata = { title: 'Terms of use | Huddle', description: 'How Huddle works, how to manage your account and content, and the current status of planned subscriptions.', alternates: { canonical: '/en/terms', languages: { 'zh-TW': '/terms', en: '/en/terms' } } }
export default function TermsPage() {
  return <LegalPage page="terms" locale="en" title="Terms of use" intro="Learn what Huddle provides, how to use it, and how to manage your content and account.">
    <LegalSection title="What Huddle provides"><p>Huddle is a personal workspace for tasks, calendars, focus sessions, notes and whiteboards. The web and desktop apps sync through the same account. Signing in, accessing cloud content and syncing require an internet connection. Refer to the website’s download section for desktop beta installation instructions and supported platforms.</p></LegalSection>
    <LegalSection title="Your account and safe use"><p>Use only sign-in credentials you are authorized to use, and keep passwords and verification links secure. Do not use someone else’s account, access content without permission, distribute malicious software or interfere with the service. If you do not have the legal capacity to enter into a contract independently, ask your legal representative to help you understand and use the service.</p></LegalSection>
    <LegalSection title="Your content and sharing"><p>Using Huddle does not transfer ownership of the tasks, notes or images you create or upload. The service needs to process that content to display, store and sync it, and to carry out sharing you choose to enable. Only upload material you have the right to use. Check the recipients and scope before sharing, and do not share others’ confidential information or content that infringes their rights.</p></LegalSection>
    <LegalSection title="Free access and planned subscriptions"><p>Pro subscriptions are not currently available for purchase. The website’s planned Taiwan prices of TWD 149 per month and TWD 1,290 per year are proposals, not active offers for purchase. If subscriptions become available, the actual features, billing period, price, automatic renewal terms and cancellation process will be shown before you confirm payment. An existing free account will not automatically become a paid subscription.</p></LegalSection>
    <LegalSection title="Updates and keeping your content"><p>Huddle continues to receive improvements and fixes. Maintenance or network outages may temporarily affect access. Keep your own copies of important content. If syncing fails, preserve any unsynced work before following the guidance on our <Link href="/en/support">help page</Link>.</p><p>Changes to payment terms or existing usage rights should be accompanied by appropriate notice and handling arrangements before taking effect. These terms do not exclude your statutory rights or any liability that cannot lawfully be excluded.</p></LegalSection>
    <LegalSection title="Account deletion and reporting issues"><p>You can choose “Delete account” in Huddle’s settings and confirm the operation. Save any content you need first. Read our <Link href="/en/privacy">privacy notice</Link> for information about deletion and data processing. If you purchase a subscription through an app store in the future, deleting your account or uninstalling the app will not cancel that subscription; you will need to follow the original store’s cancellation process.</p><p>Current technical reporting options are listed on our <Link href="/en/support">help page</Link>. This page does not mean that Huddle has enabled billing, received app store approval or passed a payment provider’s review.</p></LegalSection>
  </LegalPage>
}
