import type { Metadata } from 'next'
import Link from 'next/link'
import { LegalPage, LegalSection } from '@/components/legal/legal-page'
export const metadata: Metadata = { title: 'Help | Huddle', description: 'Help with Huddle sign-in, desktop installation, syncing, technical reports and account deletion.', alternates: { canonical: '/en/support', languages: { 'zh-TW': '/support', en: '/en/support' } } }
export default function SupportPage() {
  return <LegalPage page="support" locale="en" title="Help" intro="Start here if you need help signing in, syncing your work or installing the app.">
    <LegalSection title="Signing in to the desktop app"><p>Google sign-in opens your system browser. After authentication, choose “Open Huddle” to return to the desktop app. If you cancel or the request times out, start again from the sign-in screen. Do not post sign-in URLs or verification codes publicly.</p><p>If you cannot sign in on desktop, try the <Link href="/login">web app</Link> to check access to your account. Use the latest installer provided on the website.</p></LegalSection>
    <LegalSection title="Syncing or loading problems"><p>Check your internet connection and confirm that you are using the same account. Preserve any unsynced content before refreshing the page or reopening the app. Do not delete your account to try to fix a loading problem.</p></LegalSection>
    <LegalSection title="Reporting a technical problem"><p>You can currently report general technical issues on the <a href="https://github.com/dropout-tech/waddle/issues" target="_blank" rel="noreferrer">GitHub issue page</a>, which requires a GitHub account. Include your operating system, browser or desktop app version, the time of the issue, steps to reproduce it and screenshots with private information removed.</p><p>This is a public discussion area, not a private support inbox. Do not post passwords, verification codes, sign-in links, billing receipts, full email addresses or private work content. A private channel for billing and personal data requests is not currently available through this page.</p></LegalSection>
    <LegalSection title="Managing data and deleting your account"><p>After signing in, open settings, find “Delete account” and read the confirmation before proceeding. This action is irreversible; save any content you want to keep first. If you cannot sign in, try <Link href="/forgot-password">resetting your password</Link> or using your original Google or Apple sign-in method to regain access.</p><p>See our <Link href="/en/privacy">privacy notice</Link> for data use and deletion limitations. This page provides instructions; it is not a separate account deletion request form that can be submitted without signing in.</p></LegalSection>
    <LegalSection title="Subscription questions"><p>Pro subscriptions are not available yet. Guidance for future subscription management is on the <Link href="/en/refunds">cancellation and refunds page</Link>. You do not currently need to provide a credit card to create an account or sign in.</p></LegalSection>
  </LegalPage>
}
