import type { Metadata } from 'next'
import Link from 'next/link'
import { LegalPage, LegalSection, OperatorBlock } from '@/components/legal/legal-page'
import { WebOnly } from '@/components/legal/web-only'
import { SUPPORT_PHONE, SUPPORT_PHONE_TEL } from '@/lib/legal/operator'
export const metadata: Metadata = { title: 'Help | Huddle', description: 'Help with Huddle sign-in, desktop installation, syncing, technical reports and account deletion.', alternates: { canonical: '/en/support', languages: { 'zh-TW': '/support', en: '/en/support' } } }
export default function SupportPage() {
  return <LegalPage page="support" locale="en" title="Help" intro="Start here if you need help signing in, syncing your work or installing the app.">
    <LegalSection title="Signing in to the desktop app"><p>Google sign-in opens your system browser. After authentication, choose “Open Huddle” to return to the desktop app. If you cancel or the request times out, start again from the sign-in screen. Do not post sign-in URLs or verification codes publicly.</p><p>If you cannot sign in on desktop, try the <Link href="/login">web app</Link> to check access to your account. Use the latest installer provided on the website.</p></LegalSection>
    <LegalSection title="Syncing or loading problems"><p>Check your internet connection and confirm that you are using the same account. Preserve any unsynced content before refreshing the page or reopening the app. Do not delete your account to try to fix a loading problem.</p></LegalSection>
    <LegalSection title="Reporting a technical problem"><p>You can currently report general technical issues on the <a href="https://github.com/dropout-tech/waddle/issues" target="_blank" rel="noreferrer">GitHub issue page</a>, which requires a GitHub account. Include your operating system, browser or desktop app version, the time of the issue, steps to reproduce it and screenshots with private information removed.</p><p>This is a public discussion area, not a private support inbox. Do not post passwords, verification codes, sign-in links, billing receipts, full email addresses or private work content. For billing, refunds, withdrawal from a contract, complaints and personal data requests, call <a href={SUPPORT_PHONE_TEL}>{SUPPORT_PHONE}</a> instead.</p></LegalSection>
    <LegalSection title="Managing data and deleting your account"><p>After signing in, open settings, find “Delete account” and read the confirmation before proceeding. This action is irreversible; save any content you want to keep first. If you cannot sign in, use your original Google or Apple sign-in method to regain access.</p><p>See our <Link href="/en/privacy">privacy notice</Link> for data use and deletion limitations. This page provides instructions; it is not a separate account deletion request form that can be submitted without signing in. If you cannot sign in but need to delete your account or make a personal data request, call <a href={SUPPORT_PHONE_TEL}>{SUPPORT_PHONE}</a>. We will confirm that you own the account before acting on the request.</p></LegalSection>
    <LegalSection title="Subscription and billing questions"><p>Pro subscriptions are not available yet. Guidance for future subscription management is on the <Link href="/en/refunds">cancellation and refunds page</Link>. You do not currently need to provide a credit card to create an account or sign in.</p><WebOnly><p>Once website purchases open, you will be able to buy Huddle Pro by credit card on the Huddle website (with a 2-week free trial the first time you start). Pricing, auto-renewal, cancellation, the 7-day refund and failed payments are explained on the <Link href="/en/refunds">cancellation and refunds page</Link>. For a website subscription, sign in and go to Settings → Subscription to manage it, cancel it or change your card.</p></WebOnly><p>For a subscription bought through Apple, go to Settings → your name → Subscriptions on your iPhone or iPad. If Pro is not active after a purchase, check that you are signed in to the Huddle account you used to buy; if it is still not active, call <a href={SUPPORT_PHONE_TEL}>{SUPPORT_PHONE}</a> with your order ID or receipt ready. Do not tell us your full card number.</p></LegalSection>
    <OperatorBlock english title="Contact us" />
  </LegalPage>
}
