#!/usr/bin/env node
/**
 * Regenerates the self-hosted font files + CSS under app/fonts/ and
 * components/marketing/poster-fonts.css.
 *
 * Why this exists: production builds used to pull Geist / Geist Mono /
 * Noto Sans TC / Barlow Condensed through next/font/google, which downloads
 * ~220 woff2 slices from Google on EVERY build. One flaky fetch on the build
 * server fails the whole deploy (2026-10-01, Zeabur). The fonts are now
 * committed; builds need no network.
 *
 * You only need this script to add a weight/family or pick up a new upstream
 * font version. It copies exactly what next/font/google emits, so the
 * unicode-range slicing and fallback metrics stay identical:
 *
 *   1. temporarily restore the next/font/google declarations (see git history of app/layout.tsx and
 *      components/marketing/marketing-page.tsx, commit before this script).
 *   2. pnpm build            (needs network to fonts.googleapis.com)
 *   3. node scripts/fonts/vendor-fonts.mjs
 *   4. revert step 1, rebuild, run scripts/e2e/font-selfhost-verify.mjs
 *
 * Do not hand-edit the generated CSS.
 */
import { copyFileSync, mkdirSync, readdirSync, readFileSync, writeFileSync } from 'node:fs'
import path from 'node:path'

const root = process.cwd()
const chunksDir = path.join(root, '.next/static/chunks')
const mediaDir = path.join(root, '.next/static/media')
const filesDir = path.join(root, 'app/fonts/files')
mkdirSync(filesDir, { recursive: true })

const targets = {
  app: { file: path.join(root, 'app/fonts/app-fonts.css'), cls: 'huddle-app-fonts', faces: [], vars: [], preload: [] },
  poster: {
    file: path.join(root, 'components/marketing/poster-fonts.css'),
    cls: 'huddle-poster-fonts',
    faces: [],
    vars: [],
    preload: [],
  },
}

const cssFiles = readdirSync(chunksDir, { recursive: true })
  .filter((f) => String(f).endsWith('.css'))
  .map((f) => path.join(chunksDir, String(f)))
  .sort()

for (const cssFile of cssFiles) {
  const css = readFileSync(cssFile, 'utf8')
  if (!css.includes('@font-face')) continue
  const target = css.includes('--poster-') ? targets.poster : targets.app
  for (const [face] of css.matchAll(/@font-face\s*\{[^}]*\}/g)) {
    const rewritten = face.replace(/url\(([^)]*\/media\/)([^)]+?\.woff2)\)/g, (_m, _dir, name) => {
      // "<hash>-s.p.<hash>.woff2": the ".p." marks the slices next/font preloads.
      const short = `${name.split(/[-.]/)[0]}.woff2`
      copyFileSync(path.join(mediaDir, name), path.join(filesDir, short))
      const rel = path.relative(path.dirname(target.file), path.join(filesDir, short)).split(path.sep).join('/')
      if (/-s\.p\./.test(name)) target.preload.push(short)
      return `url(${rel.startsWith('.') ? rel : './' + rel})`
    })
    target.faces.push(rewritten)
  }
  for (const [, decl] of css.matchAll(/\.[\w-]+__variable\s*\{([^}]*)\}/g)) target.vars.push(decl.trim().replace(/;$/, ''))
}

for (const [name, t] of Object.entries(targets)) {
  if (!t.faces.length) throw new Error(`No @font-face rules found for "${name}" — run \`pnpm build\` with next/font/google restored first.`)
  const out = [
    '/* GENERATED by scripts/fonts/vendor-fonts.mjs — do not edit by hand. */',
    `/* Preloaded slices: ${[...new Set(t.preload)].join(', ') || 'none'} */`,
    ...t.faces,
    `.${t.cls}{${[...new Set(t.vars)].sort().join(';')}}`,
    '',
  ].join('\n')
  writeFileSync(t.file, out)
  console.log(`${path.relative(root, t.file)}: ${t.faces.length} @font-face, vars: ${t.vars.length}, preload: ${[...new Set(t.preload)].join(', ')}`)
}
console.log(`app/fonts/files: ${readdirSync(filesDir).length} files`)
