// Demo workspaces seeded for any user who is *not* the owner.
// Designed to (a) demo all the main features at a glance, (b) give the user
// something to click through during the onboarding spotlight tour, and (c)
// be safe to delete — none of the content is user-specific.

import type { Workspace, TimeBlock } from './types'
import { toDateString } from './calendar-utils'
import { WORKSPACE_COLORS } from './palette'

const today = new Date()
const tomorrow = new Date(today)
tomorrow.setDate(tomorrow.getDate() + 1)
const nextWeek = new Date(today)
nextWeek.setDate(nextWeek.getDate() + 7)

const TODAY = toDateString(today)
const TOMORROW = toDateString(tomorrow)
const NEXT_WEEK = toDateString(nextWeek)

const NOW = new Date().toISOString()

export const demoWorkspaces: Workspace[] = [
  {
    id: 'demo-ws-1',
    name: '歡迎',
    color: WORKSPACE_COLORS.dustyLavender.hex,
    icon: '👋',
    sortOrder: 0,
    isArchived: false,
    categories: [
      {
        id: 'demo-cat-1-1',
        workspaceId: 'demo-ws-1',
        name: '快速上手',
        sortOrder: 0,
        isCollapsed: false,
        isArchived: false,
        tasks: [
          {
            id: 'demo-task-1',
            categoryId: 'demo-cat-1-1',
            workspaceId: 'demo-ws-1',
            workspaceName: '歡迎',
            workspaceColor: WORKSPACE_COLORS.dustyLavender.hex,
            categoryName: '快速上手',
            title: '點擊我看任務細節',
            description: '可以編輯標題、描述、時間、急迫度',
            taskType: 'one_time',
            urgency: 5,
            estimatedMinutes: 5,
            calendarColor: WORKSPACE_COLORS.dustyLavender.hex,
            isCompleted: false,
            sortOrder: 0,
            createdAt: NOW,
            updatedAt: NOW,
          },
          {
            id: 'demo-task-2',
            categoryId: 'demo-cat-1-1',
            workspaceId: 'demo-ws-1',
            workspaceName: '歡迎',
            workspaceColor: WORKSPACE_COLORS.dustyLavender.hex,
            categoryName: '快速上手',
            title: '勾選左邊圈圈完成任務',
            taskType: 'one_time',
            urgency: 3,
            calendarColor: WORKSPACE_COLORS.dustyLavender.hex,
            isCompleted: false,
            sortOrder: 1,
            createdAt: NOW,
            updatedAt: NOW,
          },
          {
            id: 'demo-task-3',
            categoryId: 'demo-cat-1-1',
            workspaceId: 'demo-ws-1',
            workspaceName: '歡迎',
            workspaceColor: WORKSPACE_COLORS.dustyLavender.hex,
            categoryName: '快速上手',
            title: '已完成的任務長這樣',
            description: '點圈圈可以取消勾選',
            taskType: 'one_time',
            urgency: 2,
            calendarColor: WORKSPACE_COLORS.dustyLavender.hex,
            isCompleted: true,
            completedAt: NOW,
            sortOrder: 2,
            createdAt: NOW,
            updatedAt: NOW,
          },
        ],
      },
    ],
  },
  {
    id: 'demo-ws-2',
    name: '工作',
    color: WORKSPACE_COLORS.lowChromaBlue.hex,
    icon: '💼',
    sortOrder: 1,
    isArchived: false,
    categories: [
      {
        id: 'demo-cat-2-1',
        workspaceId: 'demo-ws-2',
        name: '本週',
        sortOrder: 0,
        isCollapsed: false,
        isArchived: false,
        tasks: [
          {
            id: 'demo-task-4',
            categoryId: 'demo-cat-2-1',
            workspaceId: 'demo-ws-2',
            workspaceName: '工作',
            workspaceColor: WORKSPACE_COLORS.lowChromaBlue.hex,
            categoryName: '本週',
            title: '撰寫週報',
            description: '週五前完成',
            taskType: 'one_time',
            urgency: 6,
            estimatedMinutes: 60,
            dueDate: TOMORROW,
            scheduledDate: TODAY,
            scheduledStartTime: '14:00',
            scheduledEndTime: '15:00',
            calendarColor: WORKSPACE_COLORS.lowChromaBlue.hex,
            isCompleted: false,
            sortOrder: 0,
            createdAt: NOW,
            updatedAt: NOW,
          },
          {
            id: 'demo-task-5',
            categoryId: 'demo-cat-2-1',
            workspaceId: 'demo-ws-2',
            workspaceName: '工作',
            workspaceColor: WORKSPACE_COLORS.lowChromaBlue.hex,
            categoryName: '本週',
            title: '團隊會議',
            taskType: 'one_time',
            urgency: 7,
            estimatedMinutes: 30,
            scheduledDate: TODAY,
            scheduledStartTime: '10:00',
            scheduledEndTime: '10:30',
            calendarColor: WORKSPACE_COLORS.lowChromaBlue.hex,
            isCompleted: false,
            sortOrder: 1,
            createdAt: NOW,
            updatedAt: NOW,
          },
          {
            id: 'demo-task-6',
            categoryId: 'demo-cat-2-1',
            workspaceId: 'demo-ws-2',
            workspaceName: '工作',
            workspaceColor: WORKSPACE_COLORS.lowChromaBlue.hex,
            categoryName: '本週',
            title: '回覆客戶 email',
            taskType: 'one_time',
            urgency: 4,
            estimatedMinutes: 20,
            calendarColor: WORKSPACE_COLORS.lowChromaBlue.hex,
            isCompleted: false,
            sortOrder: 2,
            createdAt: NOW,
            updatedAt: NOW,
          },
        ],
      },
      {
        id: 'demo-cat-2-2',
        workspaceId: 'demo-ws-2',
        name: '專案',
        sortOrder: 1,
        isCollapsed: false,
        isArchived: false,
        tasks: [
          {
            id: 'demo-task-7',
            categoryId: 'demo-cat-2-2',
            workspaceId: 'demo-ws-2',
            workspaceName: '工作',
            workspaceColor: WORKSPACE_COLORS.lowChromaBlue.hex,
            categoryName: '專案',
            title: '新版本上線規劃',
            description: '需要和設計、工程一起對齊',
            taskType: 'project',
            urgency: 8,
            estimatedMinutes: 180,
            dueDate: NEXT_WEEK,
            calendarColor: WORKSPACE_COLORS.lowChromaBlue.hex,
            isCompleted: false,
            sortOrder: 0,
            createdAt: NOW,
            updatedAt: NOW,
          },
        ],
      },
    ],
  },
  {
    id: 'demo-ws-3',
    name: '個人',
    color: WORKSPACE_COLORS.sage.hex,
    icon: '🏠',
    sortOrder: 2,
    isArchived: false,
    categories: [
      {
        id: 'demo-cat-3-1',
        workspaceId: 'demo-ws-3',
        name: '生活',
        sortOrder: 0,
        isCollapsed: false,
        isArchived: false,
        tasks: [
          {
            id: 'demo-task-8',
            categoryId: 'demo-cat-3-1',
            workspaceId: 'demo-ws-3',
            workspaceName: '個人',
            workspaceColor: WORKSPACE_COLORS.sage.hex,
            categoryName: '生活',
            title: '運動 30 分鐘',
            description: '每天養成習慣',
            taskType: 'routine',
            urgency: 4,
            estimatedMinutes: 30,
            scheduledDate: TODAY,
            scheduledStartTime: '07:00',
            scheduledEndTime: '07:30',
            calendarColor: WORKSPACE_COLORS.sage.hex,
            isCompleted: false,
            sortOrder: 0,
            isRecurring: true,
            recurrence: { type: 'daily', interval: 1 },
            createdAt: NOW,
            updatedAt: NOW,
          },
          {
            id: 'demo-task-9',
            categoryId: 'demo-cat-3-1',
            workspaceId: 'demo-ws-3',
            workspaceName: '個人',
            workspaceColor: WORKSPACE_COLORS.sage.hex,
            categoryName: '生活',
            title: '買菜 + 備餐',
            taskType: 'one_time',
            urgency: 3,
            estimatedMinutes: 60,
            scheduledDate: TOMORROW,
            calendarColor: WORKSPACE_COLORS.sage.hex,
            isCompleted: false,
            sortOrder: 1,
            createdAt: NOW,
            updatedAt: NOW,
          },
        ],
      },
      {
        id: 'demo-cat-3-2',
        workspaceId: 'demo-ws-3',
        name: '學習',
        sortOrder: 1,
        isCollapsed: false,
        isArchived: false,
        tasks: [
          {
            id: 'demo-task-10',
            categoryId: 'demo-cat-3-2',
            workspaceId: 'demo-ws-3',
            workspaceName: '個人',
            workspaceColor: WORKSPACE_COLORS.sage.hex,
            categoryName: '學習',
            title: '讀《原子習慣》第三章',
            taskType: 'one_time',
            urgency: 2,
            estimatedMinutes: 45,
            calendarColor: WORKSPACE_COLORS.sage.hex,
            isCompleted: false,
            sortOrder: 0,
            createdAt: NOW,
            updatedAt: NOW,
          },
        ],
      },
    ],
  },
]

export const demoTimeBlocks: TimeBlock[] = [
  {
    id: 'demo-tb-1',
    date: TODAY,
    startTime: '12:00',
    endTime: '13:00',
    type: 'break',
    label: '午休',
    color: '#F5F5F5',
    isRecurring: true,
  },
]
