import type { Workspace, TimeBlock } from './types'

// Mock data based on the PRD seed data
export const mockWorkspaces: Workspace[] = [
  {
    id: 'ws-1',
    name: '夢想一號',
    color: '#FF6B6B',
    icon: '',
    sortOrder: 1,
    isArchived: false,
    categories: [
      {
        id: 'cat-1-1',
        workspaceId: 'ws-1',
        name: '發文',
        sortOrder: 1,
        isCollapsed: false,
        isArchived: false,
        tasks: [
          {
            id: 'task-1',
            categoryId: 'cat-1-1',
            workspaceId: 'ws-1',
            workspaceName: '夢想一號',
            workspaceColor: '#FF6B6B',
            categoryName: '發文',
            title: '樹懶訪談文',
            taskType: 'one_time',
            urgency: 1,
            estimatedMinutes: 20,
            calendarColor: '#FF6B6B',
            isCompleted: false,
            sortOrder: 1,
            scheduledDate: '2026-04-28',
            createdAt: '2026-04-28T08:00:00Z',
            updatedAt: '2026-04-28T08:00:00Z',
          },
          {
            id: 'task-2',
            categoryId: 'cat-1-1',
            workspaceId: 'ws-1',
            workspaceName: '夢想一號',
            workspaceColor: '#FF6B6B',
            categoryName: '發文',
            title: '升級公告文',
            taskType: 'one_time',
            urgency: 4,
            estimatedMinutes: 30,
            calendarColor: '#FF6B6B',
            isCompleted: false,
            sortOrder: 2,
            scheduledDate: '2026-04-28',
            createdAt: '2026-04-28T08:00:00Z',
            updatedAt: '2026-04-28T08:00:00Z',
          },
          {
            id: 'task-3',
            categoryId: 'cat-1-1',
            workspaceId: 'ws-1',
            workspaceName: '夢想一號',
            workspaceColor: '#FF6B6B',
            categoryName: '發文',
            title: '希望小學培訓結果文',
            taskType: 'one_time',
            urgency: 4,
            estimatedMinutes: 30,
            calendarColor: '#FF6B6B',
            isCompleted: false,
            sortOrder: 3,
            createdAt: '2026-04-28T08:00:00Z',
            updatedAt: '2026-04-28T08:00:00Z',
          },
        ],
      },
      {
        id: 'cat-1-2',
        workspaceId: 'ws-1',
        name: 'web',
        sortOrder: 2,
        isCollapsed: false,
        isArchived: false,
        tasks: [
          {
            id: 'task-4',
            categoryId: 'cat-1-2',
            workspaceId: 'ws-1',
            workspaceName: '夢想一號',
            workspaceColor: '#FF6B6B',
            categoryName: 'web',
            title: '上架文',
            notes: '需要先完成審核流程',
            taskType: 'one_time',
            urgency: 3,
            estimatedMinutes: 90,
            calendarColor: '#FF6B6B',
            isCompleted: false,
            sortOrder: 1,
            scheduledDate: '2026-04-28',
            scheduledStartTime: '09:00',
            scheduledEndTime: '10:30',
            createdAt: '2026-04-28T08:00:00Z',
            updatedAt: '2026-04-28T08:00:00Z',
          },
          {
            id: 'task-5',
            categoryId: 'cat-1-2',
            workspaceId: 'ws-1',
            workspaceName: '夢想一號',
            workspaceColor: '#FF6B6B',
            categoryName: 'web',
            title: '簽約系統憑證',
            taskType: 'one_time',
            urgency: 3,
            estimatedMinutes: 120,
            calendarColor: '#FF6B6B',
            isCompleted: false,
            sortOrder: 2,
            scheduledDate: '2026-04-28',
            scheduledStartTime: '14:00',
            scheduledEndTime: '16:00',
            createdAt: '2026-04-28T08:00:00Z',
            updatedAt: '2026-04-28T08:00:00Z',
          },
          {
            id: 'task-6',
            categoryId: 'cat-1-2',
            workspaceId: 'ws-1',
            workspaceName: '夢想一號',
            workspaceColor: '#FF6B6B',
            categoryName: 'web',
            title: '測試',
            taskType: 'one_time',
            urgency: 3,
            estimatedMinutes: 60,
            calendarColor: '#FF6B6B',
            isCompleted: false,
            sortOrder: 3,
            createdAt: '2026-04-28T08:00:00Z',
            updatedAt: '2026-04-28T08:00:00Z',
          },
        ],
      },
      {
        id: 'cat-1-3',
        workspaceId: 'ws-1',
        name: '培訓',
        sortOrder: 3,
        isCollapsed: false,
        isArchived: false,
        tasks: [
          {
            id: 'task-7',
            categoryId: 'cat-1-3',
            workspaceId: 'ws-1',
            workspaceName: '夢想一號',
            workspaceColor: '#FF6B6B',
            categoryName: '培訓',
            title: '追蹤大家進度',
            description: '例行任務',
            notes: '例行任務',
            taskType: 'routine',
            urgency: 5,
            estimatedMinutes: 60,
            dueDate: '2026-04-27',
            calendarColor: '#FF6B6B',
            isCompleted: false,
            sortOrder: 1,
            scheduledDate: '2026-04-28',
            createdAt: '2026-04-28T08:00:00Z',
            updatedAt: '2026-04-28T08:00:00Z',
          },
          {
            id: 'task-8',
            categoryId: 'cat-1-3',
            workspaceId: 'ws-1',
            workspaceName: '夢想一號',
            workspaceColor: '#FF6B6B',
            categoryName: '培訓',
            title: '拍攝希望小學楓葉',
            taskType: 'one_time',
            urgency: 5,
            estimatedMinutes: 90,
            dueDate: '2026-04-27',
            calendarColor: '#FF6B6B',
            isCompleted: false,
            sortOrder: 2,
            scheduledDate: '2026-04-28',
            scheduledStartTime: '11:00',
            scheduledEndTime: '12:30',
            createdAt: '2026-04-28T08:00:00Z',
            updatedAt: '2026-04-28T08:00:00Z',
          },
          {
            id: 'task-9',
            categoryId: 'cat-1-3',
            workspaceId: 'ws-1',
            workspaceName: '夢想一號',
            workspaceColor: '#FF6B6B',
            categoryName: '培訓',
            title: '要敲定大家覆盤會一時間',
            taskType: 'one_time',
            urgency: 5,
            estimatedMinutes: 30,
            calendarColor: '#FF6B6B',
            isCompleted: false,
            sortOrder: 3,
            createdAt: '2026-04-28T08:00:00Z',
            updatedAt: '2026-04-28T08:00:00Z',
          },
        ],
      },
      {
        id: 'cat-1-4',
        workspaceId: 'ws-1',
        name: '師培總監',
        sortOrder: 4,
        isCollapsed: false,
        isArchived: false,
        tasks: [
          {
            id: 'task-10',
            categoryId: 'cat-1-4',
            workspaceId: 'ws-1',
            workspaceName: '夢想一號',
            workspaceColor: '#FF6B6B',
            categoryName: '師培總監',
            title: 'Q2 策略制定與規劃',
            taskType: 'project',
            urgency: 3,
            estimatedMinutes: 120,
            calendarColor: '#FF6B6B',
            isCompleted: false,
            sortOrder: 1,
            createdAt: '2026-04-28T08:00:00Z',
            updatedAt: '2026-04-28T08:00:00Z',
          },
          {
            id: 'task-11',
            categoryId: 'cat-1-4',
            workspaceId: 'ws-1',
            workspaceName: '夢想一號',
            workspaceColor: '#FF6B6B',
            categoryName: '師培總監',
            title: '確認大家薪資都有登記到',
            notes: '記得在 4/30 前完成',
            taskType: 'one_time',
            urgency: 5,
            estimatedMinutes: 30,
            dueDate: '2026-04-27',
            calendarColor: '#FF6B6B',
            isCompleted: false,
            sortOrder: 2,
            scheduledDate: '2026-04-28',
            createdAt: '2026-04-28T08:00:00Z',
            updatedAt: '2026-04-28T08:00:00Z',
          },
          {
            id: 'task-12',
            categoryId: 'cat-1-4',
            workspaceId: 'ws-1',
            workspaceName: '夢想一號',
            workspaceColor: '#FF6B6B',
            categoryName: '師培總監',
            title: '講師制度調整思考',
            taskType: 'one_time',
            urgency: 3,
            estimatedMinutes: 60,
            calendarColor: '#FF6B6B',
            isCompleted: false,
            sortOrder: 3,
            createdAt: '2026-04-28T08:00:00Z',
            updatedAt: '2026-04-28T08:00:00Z',
          },
        ],
      },
      {
        id: 'cat-1-5',
        workspaceId: 'ws-1',
        name: '訪談',
        sortOrder: 5,
        isCollapsed: false,
        isArchived: false,
        tasks: [
          {
            id: 'task-13',
            categoryId: 'cat-1-5',
            workspaceId: 'ws-1',
            workspaceName: '夢想一號',
            workspaceColor: '#FF6B6B',
            categoryName: '訪談',
            title: '肉圓敲時間',
            taskType: 'one_time',
            urgency: 4,
            calendarColor: '#FF6B6B',
            isCompleted: false,
            sortOrder: 1,
            createdAt: '2026-04-28T08:00:00Z',
            updatedAt: '2026-04-28T08:00:00Z',
          },
          {
            id: 'task-14',
            categoryId: 'cat-1-5',
            workspaceId: 'ws-1',
            workspaceName: '夢想一號',
            workspaceColor: '#FF6B6B',
            categoryName: '訪談',
            title: '約新的人來訪談',
            taskType: 'one_time',
            urgency: 3,
            calendarColor: '#FF6B6B',
            isCompleted: false,
            sortOrder: 2,
            createdAt: '2026-04-28T08:00:00Z',
            updatedAt: '2026-04-28T08:00:00Z',
          },
        ],
      },
    ],
  },
  {
    id: 'ws-2',
    name: '琢奧',
    color: '#4A90D9',
    icon: '',
    sortOrder: 2,
    isArchived: false,
    categories: [
      {
        id: 'cat-2-1',
        workspaceId: 'ws-2',
        name: "Let's Play",
        sortOrder: 1,
        isCollapsed: false,
        isArchived: false,
        tasks: [
          {
            id: 'task-15',
            categoryId: 'cat-2-1',
            workspaceId: 'ws-2',
            workspaceName: '琢奧',
            workspaceColor: '#4A90D9',
            categoryName: "Let's Play",
            title: '收款時間',
            taskType: 'one_time',
            urgency: 5,
            estimatedMinutes: 40,
            calendarColor: '#4A90D9',
            isCompleted: false,
            sortOrder: 1,
            scheduledDate: '2026-04-28',
            createdAt: '2026-04-28T08:00:00Z',
            updatedAt: '2026-04-28T08:00:00Z',
          },
          {
            id: 'task-16',
            categoryId: 'cat-2-1',
            workspaceId: 'ws-2',
            workspaceName: '琢奧',
            workspaceColor: '#4A90D9',
            categoryName: "Let's Play",
            title: 'QA製作',
            taskType: 'one_time',
            urgency: 5,
            estimatedMinutes: 60,
            calendarColor: '#4A90D9',
            isCompleted: false,
            sortOrder: 2,
            createdAt: '2026-04-28T08:00:00Z',
            updatedAt: '2026-04-28T08:00:00Z',
          },
          {
            id: 'task-17',
            categoryId: 'cat-2-1',
            workspaceId: 'ws-2',
            workspaceName: '琢奧',
            workspaceColor: '#4A90D9',
            categoryName: "Let's Play",
            title: '個人報名系統規劃',
            taskType: 'project',
            urgency: 4,
            estimatedMinutes: 60,
            calendarColor: '#4A90D9',
            isCompleted: false,
            sortOrder: 3,
            createdAt: '2026-04-28T08:00:00Z',
            updatedAt: '2026-04-28T08:00:00Z',
          },
          {
            id: 'task-18',
            categoryId: 'cat-2-1',
            workspaceId: 'ws-2',
            workspaceName: '琢奧',
            workspaceColor: '#4A90D9',
            categoryName: "Let's Play",
            title: '提醒大家要記得開會',
            taskType: 'one_time',
            urgency: 2,
            estimatedMinutes: 5,
            calendarColor: '#4A90D9',
            isCompleted: false,
            sortOrder: 4,
            createdAt: '2026-04-28T08:00:00Z',
            updatedAt: '2026-04-28T08:00:00Z',
          },
        ],
      },
    ],
  },
  {
    id: 'ws-3',
    name: '個人',
    color: '#66BB6A',
    icon: '',
    sortOrder: 3,
    isArchived: false,
    categories: [
      {
        id: 'cat-3-1',
        workspaceId: 'ws-3',
        name: '行程',
        sortOrder: 1,
        isCollapsed: false,
        isArchived: false,
        tasks: [
          {
            id: 'task-19',
            categoryId: 'cat-3-1',
            workspaceId: 'ws-3',
            workspaceName: '個人',
            workspaceColor: '#66BB6A',
            categoryName: '行程',
            title: '看牙醫',
            taskType: 'one_time',
            urgency: 7,
            estimatedMinutes: 60,
            dueDate: '2026-04-29',
            calendarColor: '#66BB6A',
            isCompleted: false,
            sortOrder: 1,
            scheduledDate: '2026-04-29',
            createdAt: '2026-04-28T08:00:00Z',
            updatedAt: '2026-04-28T08:00:00Z',
          },
        ],
      },
      {
        id: 'cat-3-2',
        workspaceId: 'ws-3',
        name: '學習',
        sortOrder: 2,
        isCollapsed: false,
        isArchived: false,
        tasks: [
          {
            id: 'task-20',
            categoryId: 'cat-3-2',
            workspaceId: 'ws-3',
            workspaceName: '個人',
            workspaceColor: '#66BB6A',
            categoryName: '學習',
            title: 'Vite 8 新架構研究',
            taskType: 'one_time',
            urgency: 3,
            estimatedMinutes: 45,
            calendarColor: '#66BB6A',
            isCompleted: false,
            sortOrder: 1,
            createdAt: '2026-04-28T08:00:00Z',
            updatedAt: '2026-04-28T08:00:00Z',
          },
        ],
      },
      {
        id: 'cat-3-3',
        workspaceId: 'ws-3',
        name: '其他',
        sortOrder: 3,
        isCollapsed: false,
        isArchived: false,
        tasks: [
          {
            id: 'task-21',
            categoryId: 'cat-3-3',
            workspaceId: 'ws-3',
            workspaceName: '個人',
            workspaceColor: '#66BB6A',
            categoryName: '其他',
            title: '自己的薪資也要記得登記',
            taskType: 'one_time',
            urgency: 4,
            estimatedMinutes: 20,
            calendarColor: '#66BB6A',
            isCompleted: false,
            sortOrder: 1,
            createdAt: '2026-04-28T08:00:00Z',
            updatedAt: '2026-04-28T08:00:00Z',
          },
          {
            id: 'task-22',
            categoryId: 'cat-3-3',
            workspaceId: 'ws-3',
            workspaceName: '個人',
            workspaceColor: '#66BB6A',
            categoryName: '其他',
            title: '宜蘭棋院的東西',
            taskType: 'one_time',
            urgency: 4,
            estimatedMinutes: 30,
            calendarColor: '#66BB6A',
            isCompleted: false,
            sortOrder: 2,
            createdAt: '2026-04-28T08:00:00Z',
            updatedAt: '2026-04-28T08:00:00Z',
          },
        ],
      },
    ],
  },
]

export const mockTimeBlocks: TimeBlock[] = [
  {
    id: 'tb-1',
    date: '2026-04-28',
    startTime: '12:00',
    endTime: '13:00',
    type: 'break',
    label: '午休',
    color: '#F5F5F5',
    isRecurring: true,
  },
  {
    id: 'tb-2',
    date: '2026-04-28',
    startTime: '16:00',
    endTime: '16:30',
    type: 'buffer',
    label: '緩衝時間',
    color: '#FFF8E1',
    isRecurring: false,
  },
]

// Helper to get all tasks flattened
export function getAllTasks() {
  const tasks: typeof mockWorkspaces[0]['categories'][0]['tasks'] = []
  for (const workspace of mockWorkspaces) {
    for (const category of workspace.categories) {
      tasks.push(...category.tasks)
    }
  }
  return tasks
}

// Helper to get tasks for a specific date
export function getTasksForDate(date: string) {
  return getAllTasks().filter((task) => task.scheduledDate === date)
}

// Helper to get pending tasks (no time scheduled) for a date
export function getPendingTasksForDate(date: string) {
  return getAllTasks().filter(
    (task) =>
      task.scheduledDate === date &&
      !task.scheduledStartTime &&
      !task.isCompleted
  )
}

// Helper to get scheduled tasks (with time) for a date
export function getScheduledTasksForDate(date: string) {
  return getAllTasks().filter(
    (task) =>
      task.scheduledDate === date &&
      task.scheduledStartTime &&
      task.scheduledEndTime
  )
}
