/**
 * The penguin's jokes — puns and wordplay, written natively per language.
 * NOT translations of each other: 中文 lines play on Chinese homophones
 * (魚/餘/愉、冰/兵/拼、滑/話/划、凍/懂/動、鰭/奇、呱/誇、脂/支…), English
 * lines on English puns. Chinese mode only draws from JOKES_ZH, English mode
 * only from JOKES_EN. Append only — ids are positional (`joke-zh-<n>` /
 * `joke-en-<n>`) and key the 24h no-repeat memory.
 */

export const JOKES_ZH: string[] = [
  '為什麼企鵝一早就想吃魚？因為牠一起床就「起餓」了。',
  '企鵝最喜歡星期幾？星期五，因為可以「魚」快一下。',
  '企鵝的人生哲學：年年有魚，天天有「餘」。',
  '呱！這不是叫聲，是在說你今天表現「呱呱叫」。',
  '企鵝為什麼不怕考試？因為牠天生「冰」雪聰明。',
  '企鵝當兵要去哪裡報到？「冰」營。',
  '企鵝怎麼跟人打招呼？「冰」安！',
  '企鵝為什麼不寫日記？因為每天都很「冰」凡。',
  '企鵝的座右銘：「滑」說得好，不如做得好。',
  '開會時企鵝舉鰭：「我先『滑』兩句。」',
  '企鵝開會最怕什麼？怕大家都在「划」水。',
  '老闆說開會前要先「破冰」，企鵝就真的去拿槌子了。',
  '什麼魚最容易被嚇到？「驚」魚。',
  '你這個點子真是「鰭」思妙想。',
  '企鵝一直拍手，是因為覺得你是個「鰭」才。',
  '你今天好「鰭」怪喔——很棒的那種。',
  '企鵝說自己很「凍」事，從不讓人操心。',
  '別擔心，你的辛苦我都「凍」。',
  '遇到難題，企鵝的步驟：先冷靜，再「凍」手。',
  '天冷更要「凍」起來！',
  '企鵝的健身口號：「凍」次打次！',
  '企鵝講完冷笑話，全場都「凍」容了。',
  '企鵝把錢存在哪？「冰」行。',
  '企鵝說錯話會道歉：「不好意思，我剛剛『滑』錯了。」',
  '企鵝為什麼不會迷路？因為牠很有「魚」感。',
  '我對今天有個好「魚」感。',
  '企鵝說話永遠留點「餘」地——留給魚。',
  '這份工作我「游」刃有餘，畢竟我真的會游。',
  '企鵝很有「脂」氣，脂肪多的那種。',
  '企鵝不減肥，因為要保持「脂」持你。',
  '企鵝處事原則：「冰」持初衷。',
  '企鵝的名片上寫：「冰」來將擋，水來我游。',
  '企鵝最怕去哪個地方？「滑」鐵盧。',
  '企鵝從來不會「冷」落你。',
  '冰凍三尺非一日之寒，待辦三頁非一日之懶。',
  '「魚」其拖延，不如現在就做。',
  '「魚」其抱怨，不如先吃條魚。',
  '企鵝的健康祕訣：沒「冰」沒痛就是福。',
  '企鵝最愛說：「這也太『呱』張了吧！」',
  '我要「呱」獎你一下：做得好！',
  '企鵝為什麼喜歡開會？因為可以「魚」會。',
  '企鵝最喜歡的成語？如「魚」得水。最討厭的？「熱」血沸騰。',
  '企鵝最愛的球類運動？「冰」球，不用猜。',
  '企鵝不滑手機，怕被「冰」蔽。',
  '企鵝屏住呼吸等你下一步，這叫「冰」息以待。',
  '企鵝說人生很簡單：划得來就「滑」，划不來就躺。',
  '企鵝最常用的交通工具？肚子。「滑」算又環保。',
  '企鵝說：「凡事不要想太多，想太多會『凍』結。」',
  '企鵝的待辦清單不叫待辦，叫「待滑」。',
  '企鵝最常說的鼓勵：「你很棒，這件事一點都不『冰』難。」',
  '企鵝的偶像是冰箱，因為它永遠「冷」靜又「凍」事。',
  '企鵝說：「我不是在發呆，我在『冰』思。」',
  '企鵝請假理由：「我今天有點『凍』不了。」',
  '企鵝最喜歡的季節是冬天，因為牠可以「冬」奔西跑。',
  '企鵝去市場賣瓜，一直喊：「自賣自『呱』！」',
  '企鵝上台報告前說：「讓我先『冰』復一下心情。」',
  '企鵝最重視團隊合作，大家要「鰭」心協力。',
  '這週的任務，我們「鰭」頭並進！',
  '看完你的報告，企鵝只想說：真是讓人「呱」目相看。',
  '企鵝對每一條魚都說：「『魚』你相遇，真好。」',
]

export const JOKES_EN: string[] = [
  'What do penguins wear on their heads? Ice caps.',
  'I\'m not slacking. I\'m just chilling.',
  'Let\'s not waddle around the point.',
  'This meeting could have been an ice-mail.',
  'Why don\'t fish attend meetings? They can\'t find the porpoise.',
  'Let\'s hope this meeting has a porpoise.',
  'I asked an iceberg for career advice. It said, "Just go with the floe."',
  'Go with the floe today.',
  'Snow problem. We\'ve got this.',
  'Ice to see you working. Snow kidding.',
  'Who\'s a penguin\'s favorite relative? Aunt Arctica.',
  'How do penguins make tough decisions? They flipper a coin.',
  'Fish puns? I\'m only doing them for the halibut.',
  'Is it just me, or is this task a little fishy?',
  'That idea is o-fish-ally great.',
  'Water you working on? Looks fin-tastic.',
  'Let minnow if you need anything.',
  'Don\'t be koi. Ask for help.',
  'That task list? Totally krill-able.',
  'This bug is small fry. You\'ll catch it.',
  'Your inbox? That\'s just the tip of the iceberg.',
  'I have a to-do list and a to-dive list.',
  'I left my to-do list in the fridge. Now it\'s a cool-do list.',
  'Let\'s put that on ice for now.',
  'Why did the iceberg get promoted? It had real depth.',
  'What do icebergs do after work? Chill.',
  'Brrr-illiant work today.',
  'Your focus is un-brrr-lievable.',
  'My favorite kind of meeting? A brrr-ainstorm.',
  'A penguin\'s favorite month? Brrr-uary.',
  'I sea what you did there.',
  'Keep calm and waddle on.',
  'I don\'t procrastinate. I let my tasks chill first.',
  'Deadlines don\'t scare me. I\'ve faced much colder things.',
  'Penguins never panic about deadlines. We just keep our cool.',
  'I was going to start that task, but I got cold feet.',
  'Let\'s not get cold feet about that proposal.',
  'Let\'s tackle this one fin at a time.',
  'Take five. Or take fish. Both are brain food.',
  'I\'m on a roll. A sushi roll.',
  'Some call it waddling. I call it agile movement.',
  'I tried multitasking once. Now I just multi-flap.',
  'I\'m basically a pen with extra guin. Ready to take notes.',
  'I\'m not being flippant. I\'m being flipper-nt.',
  'How do penguins build their houses? Igloos them together.',
  'Where do penguins keep their savings? In a snow bank.',
  'What\'s a penguin\'s favorite salad? Iceberg, obviously.',
  'Seal the deal. I\'ll bring the seal.',
  'That report went swimmingly.',
  'Stay frosty, friend.',
  'Tuna in: you\'re doing great.',
  'Meet me by the water cooler. It\'s basically my natural habitat.',
  'I\'m not late. I\'m fashionably frozen.',
  'What\'s a penguin\'s favorite workout? Ice-ometrics.',
  'That task was slippery, but you skated right through it.',
  'Penguins make great coworkers. We always dress for the job we want.',
  'My budget isn\'t tight. It\'s frozen.',
  'End of the day? Time to chill out. Literally.',
  'Good work today. I\'m not squidding.',
  'You\'re doing a whale of a job.',
  'Don\'t clam up in the meeting. Your ideas are pearls.',
  'Shell we get started on the next task?',
]
